### ISSUE TITLE
Links under the Contents section on website don't work

### ISSUE THREAD

**Issue by RoyaKar** [aneagoie/ztm-python-cheat-sheet#2] opened 2019-10-01 06:25 UTC
Hi! 
The section titles (links) on the left hand side under Contents, don't seem to be working.

**Comment by alexroseb** [comment] 2019-10-03 14:54
They're working for me - could you please elaborate on what's wrong?

**Comment by Maximus06** [comment] 2019-10-04 19:00
Hi
It does not work for me either. In fact the left link are different from the top link (under content).
Exemple for the link number on the left:
https://nicedoc.io/aneagoie/ztm-python-cheat-sheet?theme=dark#**user-content-**numbers
On the top (works fine):
https://nicedoc.io/aneagoie/ztm-python-cheat-sheet?theme=dark#numbers
All the left links have **user-content-**

**Comment by PlusleNMinun** [comment] 2019-10-06 15:57
The side contents bar links also do not work for me.

**Comment by aneagoie** [comment] 2019-10-06 17:46
Hey everyone! This was actually the intended behaviour: the side was meant to be just an "Outline" and the top headers the actual link to each section. If you feel like the side should also link to the sections, feel free to make a Pull Request with the changes since this cheat sheet is open sourced and can be modified/improved by anyone!

**Comment by RoyaKar** [comment] 2019-10-08 02:48
Hi @aneagoie!
I've made a Pull Request but unfortunately I can only view/access the ReadMe.md file and the git folder. I can't seem to access the HTML and/or the JS file to make the appropriate edits. Apologies if I've missed something as I'm pretty new to Github.

**Comment by aneagoie** [comment] 2019-10-08 09:37
@RoyaKar the way it works is that nicedoc.io is a 3rd party service that reads from the README, so even for myself, the only thing that I can change is the README. 

To test on your end, fork this repository, and got to your own project in nicedoc: nicedoc.io/<your github username>/<repository name>

As you update the README there, you should see it update at the above URL. 

Hope that helps :)

**Comment by RoyaKar** [comment] 2019-10-09 09:06
@aneagoie It looks like the content (on the left side of the webpage) is just something that nicedoc automatically add on. I can't find it anywhere in the README file to edit. 

Anyone else have any ideas on how we can add links? @alexroseb @Maximus06 @PlusleNMinun ?

**Comment by aneagoie** [comment] 2019-10-09 10:19
Looking at the examples they provide this is the only one that has the left hand side navigable: https://nicedoc.io/cyrilwanner/next-optimized-image
So it is doable...

**Comment by alexroseb** [comment] 2019-10-13 16:33
I'm sorry, I came to this from the github repo directly, not the nicedoc site, so the links work on github.  I think if it you want it just as a TOC without links that's good too but it shouldn't use <a> elements. I'll look into how nicedoc creates that column!

**Comment by aneagoie** [comment] 2020-02-05 12:53
Closing this issue, since we moved away from nicedoc and now hosting it on our own website here where the links work: https://zerotomastery.io/courses/python/cheatsheet/

**Closed by aneagoie** 2020-02-05 12:53 UTC
